### PR TITLE
Create libopenmpt script

### PR DESCRIPTION
**Pull request by pepijn-devries**
See also https://github.com/autobrew/bundler/pull/2

Required for https://github.com/pepijn-devries/openmpt to work on MacOS

It might need some tweaking as I cannot test it from my fork...

### CODE REVIEW

**Comment by pepijn-devries** [comment]
https://github.com/pepijn-devries/openmpt/issues/7

**Comment by jeroen** [comment]
We actually first need to properly build the library that you download in this script 😅

**Comment by pepijn-devries** [comment]
I had exactly the same problem on Windows. I had to link portaudio, but the compiler was very picky about the linking order, and it was a pain to figure out the right order (this is what worked on Windows eventually: https://github.com/pepijn-devries/openmpt/blob/master/src/Makevars.win).

> We actually first need to properly build the library that you download in this script 😅

I think your refer to the configure script of my package here, right? The actual library is built by the autobrew script as I understand it. Is there an easier way to play with the linking order than sending subsequent pull requests? On Windows it was a painstaking process of trial and error.

**Comment by jeroen** [comment]
Yes the linking order matters for static linking. I tried re-ordering the flags but this does not seem to be the problem. 

If you're on macos you can test it by building the package and hardcode `PKG_LIBS` manually in your `src/Makevars.in`

**Pull request merged**
